### PR TITLE
Fixed a minor error

### PR DESCRIPTION
**Pull request by KenaiTheWolf**
Fixed a error preventing the application from running.

### CODE REVIEW

**Comment by The-Wolf312** [comment]
Fixes a compiler error and sets the development target to a more up to date system.

**Comment by gupuru** [comment]
@The-Wolf312 
Thank you pull request!
Sorry for the delay in confirmation.

Since I see it on December 17, please wait a little more.

**Review by gupuru — APPROVED** [review]
@The-Wolf312 
Thanks!
Good jobs!

**Comment by gupuru** [comment]
kitune6

**Pull request merged**
